### ISSUE TITLE
[Bug] Readme Titles not being displayed

### ISSUE THREAD

**Issue by broken-usb** [Kesomannen/gale#48] opened 2024-07-19 23:52 UTC
# Titles like this one won't be displayed inside the Modmanager

I chose [this mod](https://thunderstore.io/c/lethal-company/p/Zaggy1024/OpenBodyCams/) as an example of the issue.
On Thunderstore this is how the description will look:
![image](https://github.com/user-attachments/assets/cb4da076-49d2-4b15-8dbf-72f61f9b25f2)
But in the Modmanager no title will be shown:
![image](https://github.com/user-attachments/assets/39306b18-86f3-48c1-ac5e-9f985aefbb27)
![image](https://github.com/user-attachments/assets/d5da3505-5be9-4d46-bb93-ab5ba0fd46c8)

This isn't a mod specific issue as this can been seen happening with any other mod.

## However, the smaller titles, like this one, will be shown properly as seen on [this mod](https://thunderstore.io/c/lethal-company/p/Zaggy1024/PathfindingLagFix/) for example
On Thunderstore:
![image](https://github.com/user-attachments/assets/59adbcef-93c5-49fd-b130-ec397f8f95ac)
On Gale:
![image](https://github.com/user-attachments/assets/43f19d3d-295c-45ca-9192-766735d56c66)
![image](https://github.com/user-attachments/assets/17600fe6-8c39-4141-aadc-4d737e0acf36)

### Additionally, summaries cannot be retracted:
![image](https://github.com/user-attachments/assets/551d2b65-34d2-47d4-81af-ed7566f10ea1)
![image](https://github.com/user-attachments/assets/91f899fa-02a3-4292-9fb1-3a30ffb73d36)

**Comment by Kesomannen** [comment] 2024-07-20 20:11
Yeah, it removes `#` titles to avoid displaying the mod name twice, but removing all of them is not intended behavior.

For the summary issue, see #49

**Comment by Kesomannen** [comment] 2024-07-30 10:32
Fixed in 0.7.0

**Closed by Kesomannen** 2024-07-30 10:32 UTC
