### ISSUE TITLE
Doesn't automatically scroll up when a list becomes shorter

### ISSUE THREAD

**Issue by Damglador** [Kesomannen/gale#82] opened 2024-08-21 12:49 UTC
For example, you scroll far down in mod browser and then change your search request, it shortens the list of results, but it doesn't move you to the end of that list. And every time I change my search request, I have to manually scroll up.
![image](https://github.com/user-attachments/assets/e7cf5df0-3f34-450c-aee5-c5acfad5fc6f)

**Comment by Damglador** [comment] 2024-08-21 21:34
Demonstration:
https://github.com/user-attachments/assets/d0c22f39-3a1a-46c2-a4f4-af2afe9ff063

**Comment by Damglador** [comment] 2024-08-21 21:36
Demonstration:
https://github.com/user-attachments/assets/47a96242-7243-49db-aa27-4849de2b2f4d

**Comment by Damglador** [comment] 2024-08-21 21:36
Demonstation:
https://github.com/user-attachments/assets/f4a00fda-bdc0-4035-8c76-6816a9555e6f

**Comment by Kesomannen** [comment] 2024-08-22 19:31
Duplicate of #67

**Closed by Kesomannen** 2024-08-22 19:31 UTC
