### ISSUE TITLE
Searching doesn't update current scroll bar position / max height 

### ISSUE THREAD

**Issue by Flamy2000** [Kesomannen/gale#97] opened 2024-08-31 00:57 UTC
If you scroll down a lot and then search for something, its possible to be scrolled down further down than the actual modlist's page height / scrollable content, causing it to look like no mods exist with that search term. Scrolling back up to the content area resets the scroll bar max height

**Comment by Kesomannen** [comment] 2024-08-31 07:17
Duplicate of #67

**Closed by Kesomannen** 2024-08-31 07:17 UTC

**Comment by Flamy2000** [comment] 2024-08-31 15:36
whoops mb
